#%RAML 0.8
title: org.opent2t.sample.hub.superpopular
version: v1.0

schemas:
  - Platform: !include org.opent2t.sample.hub.superpopular.json

traits:
  - interface-sensor:
      queryParameters:
        if:
          enum: ["oic.if.s", "oic.if.baseline"]

/:
  description: |
   Gets a list of platforms connected to a hub.
  displayName: Platforms
  is: [ interface-sensor ]

  get:
    description: |
        Retrieves the platform and their current state.
    responses:
      200:
        body:
          application/json:
            schema: Hub
            example: |
              {
                "schema": "org.opent2t.sample.hub.superpopular",
                "id": "unique_example_id",
                "platforms": {
                }
             }

/?$expand
  description: |
    Gets a list of platforms connected to a hub along with their current state.
  displayName: Platform
  is: [interface-sensor]

  get:
    description: |
      Retrieves the platforms and their current state.
    responses:
      200:
        body:
          application/json:
            schema: Platform
            example: |
              {
                "schema": "org.opent2t.sample.hub.superpopular",
                "id": "unique_example_id",
                "platforms": {
                }
             }

/platforms:
  description: |
   Gets a list of platforms connected to a hub.
  displayName: Platforms
  is: [ interface-sensor ]

  get:
    description: |
        Retrieves the platform and their current state.
    responses:
      200:
        body:
          application/json:
            schema: Hub
            example: |
              {
                "schema": "org.opent2t.sample.hub.superpopular",
                "id": "unique_example_id",
                "platforms": {
                }
             }

/platforms/?$expand
  description: |
    Gets a list of platforms connected to a hub along with their current state.
  displayName: Platform
  is: [interface-sensor]

  get:
    description: |
      Retrieves the platforms and their current state.
    responses:
      200:
        body:
          application/json:
            schema: Platform
            example: |
              {
                "schema": "org.opent2t.sample.hub.superpopular",
                "id": "unique_example_id",
                "platforms": {
                }
             }
    
