#%RAML 0.8
title: opent2t.p.hub
version: v1.0

schemas:
  - Platform: !include opent2t.p.hub.json

traits:
  - interface-sensor:
      queryParameters:
        if:
          enum: ["oic.if.s", "oic.if.baseline"]

/platforms:
  description: |
   Gets a list of platforms connected to a hub.
  displayName: Platforms
  is: [ interface-sensor ]

  get:
    description: |
        Retrieves the platform and their current state.
    responses:
      200:
        body:
          application/json:
            schema: Hub
            example: |
              {
                "schema": "opent2t.p.hub",
                "id": "unique_example_id",
                "devices": {
                },
            }

/platforms/?$expand
  description: |
    Gets a list of platforms connected to a hub along with their current state.
  displayName: Platform
  is: [interface-sensor]

  get:
    description: |
      Retrieves the platforms and their current state.
    responses:
      200:
        body:
          application/json:
            schema: Platform
            example: |
              {
                "schema": "opent2t.p.hub",
                "id": "unique_example_id",
                "devices": {
                },
            }
    
