#%RAML 0.8
title: opent2t.p.light
version: v1.0

schemas:
  - BinarySwitch: !include oic.r.switch.binary.json
  - Dimming: !include oic.r.light.dimming.json
  - Mode: !include oic.r.mode.json
  - ColourRGB: !include oic.r.colour.rgb.json
  - ColourChroma: !include oic.r.colour.chroma.json
  - LightPlatform: !include opent2t.p.light.json
  - Subscription: |
      {
        "type": "object",
        "properties": {
          "callbackUrl": { "type": "string" },
          "expiration": { "type": "number" },
          "response": { "type": "string"}
        }
      }
    

traits:
    - interface-actuator:
      queryParameters:
        if:
          enum: ["oic.if.a", "oic.if.baseline"]

  - interface-sensor:
      queryParameters:
        if:
          enum: ["oic.if.s", "oic.if.baseline"]

/:
  displayName: Platform
  get:
    responses:
      200:
        body:
          application/json:
            schema: LightPlatform
            example: |
              {
                "opent2t": {
                  "schema": "opent2t.p.outlet",
                  "translator": "opent2t-translator-com-opent2t-p-lamp@0.1.1",
                  "controlId": "123"
                },
                "pi": "8045C566-B44B-462F-A4AB-FA7FC968CE71",
                "mnmn": "Contoso",
                "n": "Bedside lamp",
                "rt": ["opent2t.p.lamp"],
                "entities": [
                  {
                    "rt": ["oic.d.lamp"],
                    "n": "Device 1",
                    "di": "A94F0FBE-9D2D-4A81-A99B-4024AADB1631",
                    "icv": "core.1.1.0",
                    "dmv": "res.1.1.0",
                    "resources": [
                      {
                        "href": "/power",
                        "rt": ["oic.r.switch.binary"],
                        "if": ["oic.if.a", "oic.if.baseline"]
                      },
                     {
                        "href": "/dim",
                        "rt": ["oic.r.light.dimming"],
                        "if": ["oic.if.a", "oic.if.baseline"]
                      },
                     {
                        "href": "/colourMode",
                        "rt": ["oic.r.mode"],
                        "if": ["oic.if.s", "oic.if.baseline"]
                      },
                     {
                        "href": "/colourRGB",
                        "rt": ["oic.r.colour.rgb"],
                        "if": ["oic.if.a", "oic.if.baseline"]
                      },
                      {
                        "href": "/colourChroma",
                        "rt": ["oic.r.colour.chroma"],
                        "if": ["oic.if.a", "oic.if.baseline"]
                      },
                    ]
                  }
                ]
              }

/?$expand
  displayName: Platform
  get:
    responses:
      200:
        body:
          application/json:
            schema: LightPlatform
            example: |
              {
                "opent2t": {
                  "schema": "opent2t.p.outlet",
                  "translator": "opent2t-translator-com-opent2t-p-lamp@0.1.1",
                  "controlId": "123"
                },
                "pi": "8045C566-B44B-462F-A4AB-FA7FC968CE71",
                "mnmn": "Contoso",
                "n": "Bedside lamp",
                "rt": ["opent2t.p.lamp"],
                "entities": [
                  {
                    "rt": ["oic.d.lamp"],
                    "n": "Device 1",
                    "di": "A94F0FBE-9D2D-4A81-A99B-4024AADB1631",
                    "icv": "core.1.1.0",
                    "dmv": "res.1.1.0",
                    "resources": [
                      {
                        "href": "/power",
                        "rt": ["oic.r.switch.binary"],
                        "if": ["oic.if.a", "oic.if.baseline"],
                        "id": "power",
                        "value": true
                      },
                      {
                        "href": "/colourrgb",
                        "rt": ["oic.r.colour.rgb"],
                        "if": ["oic.if.a", "oic.if.baseline"],
                        "id": colour,
                        "rgbValue": [255,255,255],
                        "range": [0,255]
                      },
                      {
                        "href": "/dimming",
                        "rt": ["oic.r.light.dimming"],
                        "if": ["oic.if.a", "oic.if.baseline"]
                        "id": "dimming",
                        "dimmingSetting": 30,
                        "step": 5,
                        "range": [0, 100]
                      }
                    ]
                  }
                ]
              }

/devices/{deviceid}:
  /power:
    displayName: Power
    is: [ interface-actuator ]

    get:
      responses:
        200:
          body:
            application/json:
              schema: BinarySwitch
              example: |
                {
                  "rt": ["oic.r.switch.binary"],
                  "id": "unique_example_id",
                  "value": false
                }
    post:
      body:
        application/json:
          schema: BinarySwitch
          example: |
            {
              "id": "unique_example_id",
              "value": true
            }
      responses:
        200:
          body:
            application/json:
              schema: BinarySwitch
              example: |
                {
                  "id": "unique_example_id",
                  "value": true
                }

  /colourMode:
    displayName: Colour Mode
    is: [ interface-sensor ]

    get:
      queryParameters:
           page:
             type: integer

      responses:
        200:
          body:
            application/json:
              schema: Mode
              example: |
                {
                  "rt": ["oic.r.mode"],
                  "id": "unique_example_id",
                  "modes": ["rgb"],
                  "supportedModes": ["rgb","hs", "xy", "ct"]
                }

  /colourRGB:
    displayName: Colour RGB
    is: [ interface-actuator ]

    get:
      responses:
        200:
          body:
            application/json:
              schema: ColourRGB
              example: |
                {
                  "rt": ["oic.r.colour.rgb"],
                  "id": "unique_example_id",
                  "rgbValue": [255,255,255]
                }
    post:
      body:
        application/json:
          schema: ColourRGB
          example: |
            {
              "id": "unique_example_id",
              "rgbValue": [0,0,0]
            }
      responses:
        200:
          body:
            application/json:
              schema: ColourRgb
              example: |
                {
                  "id": "unique_example_id",
                  "rgbValue": [0,0,0]
                }

  /dim:
    displayName: Dim
    is: [ interface-actuator ]

    get:
      responses:
        200:
          body:
            application/json:
              schema: Dimming
              example: |
                {
                  "rt": ["oic.r.light.dimming"],
                  "id": "unique_example_id",
                  "dimmingSetting": 30,
                  "step": 5,
                  "range": [0,100]
                }
    post:
      body:
        application/json:
          schema: Dimming
          example: |
            {
              "id": "unique_example_id",
              "dimmingSetting": 50
            }
      responses:
        200:
          body:
            application/json:
              schema: Dimming
              example: |
                {
                  "id": "unique_example_id",
                  "dimmingSetting": 50
                }

  /colourChroma:
    displayName: Colour Chroma
    is: [ interface-actuator ]

    get:
      responses:
        200:
          body:
            application/json:
              schema: ColourChroma
              example: |
                {
                  "rt":         ["oic.r.colour.chroma"],
                  "id":         "unique_example_id",
                  "hue":        13088,
                  "saturation": 212,
                  "csc":        [0.41,0.51],
                  "ct":         457
                }

    post:
      body:
        application/json:
          schema: ColourChroma
          example: |
            {
              "id":         "unique_example_id",
              "hue":        13088,
              "saturation": 212,
              "csc":        [0.41,0.51],
              "ct":         457
            }
      responses:
        200:
          body:
            application/json:
              schema: ColourChroma
              example: |
                {
                  "id":          "unique_example_id",
                  "hue":         13088,
                  "saturation":  212,
                  "csc":         [0.41,0.51],
                  "ct":          467
                }

#
# Notification subscription URIs
#

/subscribe:
  description: |
    This resource manages subscriptions to changes on this device.
  displayName: Subscribe
    
  post:
    description: |
        Creates or refreshes a subscription to this lamp.  This method can be called twice, first with
        a callback URL (verificationRequest will be ignored), and the second time with the parameters of an http GET to the
        callback Url server for verification of the subscription (in which case callback Url will be ignored). The second call
        will construct a response that should be returned to the notifications server.
    body:
      application/json:
        schema: Subscription
        example: |
          {
            "callbackUrl": "http://myserver.com",
          }    
    responses:
       200:
        body:
          application/json:
            schema: Subscription
            example: |
                {
                  "callbackUrl":"http://myserver.com",
                  "expiration": "123456678",
                  "response": { "plain text response" }
                }
       400:
          body:
            application/json:
              example: { "message": "Bad request" }
       403:
          body:
            application/json:
              example: { "message": "Subscription is denied" }

  delete:
    description: Unsubscribes to notifications to a callback Url
    body:
      application/json:
        schema: Subscription
        example: |
          {
            "callbackUrl": "http://myserver.com",
          } 
    responses:
      200:
        body:
          application/json:
          example: {}
