#%RAML 0.8
title: org.opent2t.sample.lamp.superpopular
version: v1.0

schemas:
  - Lamp: !include org.opent2t.sample.lamp.superpopular.json
  - BinarySwitch: !include oic.r.switch.binary.json
  - Dimming: !include oic.r.dimming.json
  - ColourRgb: !include oic.r.coulour.rgb.json
  - Subscription: |
      {
        "type": "object",
        "properties": {
          "callbackUrl": { "type": "string" },
          "expiration": { "type": "number" },
          "response": { "type": "string"}
        }
      }
    

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a", "oic.if.baseline"]

/:
  displayName: Platform
  get:
    responses:
      200:
        body:
          application/json:
            schema: Lamp
            example: |
              {
                "opent2t": {
                  "schema": "opent2t.p.outlet",
                  "translator": "opent2t-translator-com-opent2t-p-lamp@0.1.1",
                  "control_id": "123"
                },
                "pi": "8045C566-B44B-462F-A4AB-FA7FC968CE71",
                "mnmn": "Contoso",
                "n": "Bedside lamp",
                "rt": ["opent2t.p.lamp"],
                "entities": [
                  {
                    "rt": ["oic.d.lamp"],
                    "n": "Device 1",
                    "di": "A94F0FBE-9D2D-4A81-A99B-4024AADB1631",
                    "icv": "core.1.1.0",
                    "dmv": "res.1.1.0",
                    "resources": [
                      {
                        "href": "/power",
                        "rt": ["oic.r.switch.binary"],
                        "if": ["oic.if.a", "oic.if.baseline"]
                      },
                      {
                        "href": "/colourrgb",
                        "rt": ["oic.r.colourrgb"],
                        "if": ["oic.if.a", "oic.if.baseline"]
                      },
                      {
                        "href": "/dimming",
                        "rt": ["oic.r.dimming"],
                        "if": ["oic.if.a", "oic.if.baseline"]
                      }
                    ]
                  }
                ]
              }

/?$expand
  displayName: Platform
  get:
    responses:
      200:
        body:
          application/json:
            schema: Lamp
            example: |
              {
                "opent2t": {
                  "schema": "opent2t.p.outlet",
                  "translator": "opent2t-translator-com-opent2t-p-lamp@0.1.1",
                  "control_id": "123"
                },
                "pi": "8045C566-B44B-462F-A4AB-FA7FC968CE71",
                "mnmn": "Contoso",
                "n": "Bedside lamp",
                "rt": ["opent2t.p.lamp"],
                "entities": [
                  {
                    "rt": ["oic.d.lamp"],
                    "n": "Device 1",
                    "di": "A94F0FBE-9D2D-4A81-A99B-4024AADB1631",
                    "icv": "core.1.1.0",
                    "dmv": "res.1.1.0",
                    "resources": [
                      {
                        "href": "/power",
                        "rt": ["oic.r.switch.binary"],
                        "if": ["oic.if.a", "oic.if.baseline"],
                        "id": "power",
                        "value": true
                      },
                      {
                        "href": "/colourrgb",
                        "rt": ["oic.r.colour.rgb"],
                        "if": ["oic.if.a", "oic.if.baseline"],
                        "id": colour,
                        "rgbValue": [255,255,255],
                        "range": [0,255]
                      },
                      {
                        "href": "/dimming",
                        "rt": ["oic.r.light.dimming"],
                        "if": ["oic.if.a", "oic.if.baseline"]
                        "id": "dimming",
                        "dimmingSetting": 30,
                        "step": 5,
                        "range": [0, 100]
                      }
                    ]
                  }
                ]
              }

/device/{deviceid]/power:
  displayName: Power
  is: [ interface ]

displayName: Power
  is: [ interface]

  get:
    responses:
      200:
        body:
          application/json:
            schema: BinarySwitch
            example: |
              {
                "rt": ["oic.r.switch.binary"],
                "id": "unique_example_id",
                "value": false
              }
  post:
    body:
      application/json:
        schema: BinarySwitch
        example: |
          {
            "id": "unique_example_id",
            "value": true
          }
    responses:
      200:
        body:
          application/json:
            schema: BinarySwitch
            example: |
              {
                "id": "unique_example_id",
                "value": true
              }

/device/{deviceid]/colourrgb:
  displayName: Colour
  is: [ interface ]

  get:
    responses:
      200:
        body:
          application/json:
            schema: ColourRgb
            example: |
              {
                "rt": ["oic.r.colour.rgb"],
                "id": "unique_example_id",
                "rgbValue": [255,255,255]
              }
  post:
    body:
      application/json:
        schema: ColourRgb
        example: |
          {
            "id": "unique_example_id",
            "rgbValue": [0,0,0]
          }
    responses:
      200:
        body:
          application/json:
            schema: ColourRgb
            example: |
              {
                "id": "unique_example_id",
                "rgbValue": [0,0,0]
              }

/device/{deviceid]/dimming:
  displayName: Dimming
  is: [ interface ]

  get:
    responses:
      200:
        body:
          application/json:
            schema: Dimming
            example: |
              {
                "rt": ["oic.r.colour.rgb"],
                "id": "unique_example_id",
                "dimmingSetting": 30,
                "step": 5,
                "range": [0,100]
              }
  post:
    body:
      application/json:
        schema: Dimming
        example: |
          {
            "id": "unique_example_id",
            "dimmingSetting": 50
          }
    responses:
      200:
        body:
          application/json:
            schema: Dimming
            example: |
              {
                "id": "unique_example_id",
                "dimmingSetting": 50
              }

/SubscribeLampResURI:
  description: |
   This resource manages subscriptions to changes on this device.
  displayName: SubscribeLamp
  is: [ interface ]
    
  post:
    description: |
        Creates or refreshes a subscription to this lamp.  This method should be called twice, first with
        a callback URL (verificationRequest will be ignored), and the second time with the parameters of an http GET to the
        callback Url server for verification of the subscription (in which case callback Url will be ignored). The second call
        will construct a response that should be returned to the notifications server.
    body:
      application/json:
        schema: Subscription
        example: |
          {
            "callbackUrl": "http://myserver.com",
          }    
    responses:
       200:
        body:
          application/json:
            schema: Subscription
            example: |
                {
                  "callbackUrl":"http://myserver.com",
                  "expiration": "123456678",
                  "response": { "plain text response" }
                }
       400:
          body:
            application/json:
              example: { "message": "Bad request" }
       403:
          body:
            application/json:
              example: { "message": "Subscription is denied" }

  delete:
    description: Unsubscribes to notifications to a callback Url
    body:
      application/json:
        schema: Subscription
        example: |
          {
            "callbackUrl": "http://myserver.com",
          } 
    responses:
      200:
        body:
          application/json:
          example: {}
