#%RAML 0.8
title: org.opent2t.sample.thermostat.superpopular
version: v1.0

schemas:
  - Thermostat: !include org.opent2t.sample.thermostat.superpopular.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a"]

/ThermostatResURI:
  description: |
   This resource describes the properties associated with Thermostat.
   The resource is a composite resource.
  displayName: Thermostat
  is: [ interface ]

  get:
    description: |
        Retrieves the current resource representation
    queryParameters:
      payload:
        displayName: payload
        description: Device Schema in need of translation
        required: false
    responses:
      200:
        body:
          application/json:
            schema: Thermostat
            example: |
              {
                "rt": "org.opent2t.sample.thermostat.superpopular",
                "id": "unique_example_id",
                "ambientTemperature": {
                  "temperature": 66,
                  "units": "F"
                },
                "targetTemperature": {
                  "temperature": 66,
                  "units": "F"
                },
                "targetTemperatureHigh": {
                  "temperature": 68,
                  "units": "F"
                },
                "targetTemperatureLow": {
                  "temperature": 64,
                  "units": "F"
                }
            }
    
  post:
    body:
      application/json:
        schema: Thermostat
        example: |
          {
            "id": "unique_example_id",
            "target_temperature": {
              "temperature": 74,
              "units": "F"
            }
          }
    responses:
      200:
        body:
          application/json:
            schema: Thermostat
            example: |
                {
                    "id": "unique_example_id",
                    "target_temperature": {
                        "temperature": 74,
                        "units": "F"
                    }
                }

/SubscribeThermostatResURI:
  description: |
   This resource manages subscriptions to changes on this device.
  displayName: ThermostatSubscription
  is: [ interface ]
    
  post:
    description: Creates or refreshes a subscription to this Thermostat.
    queryParameters:
      callbackUrl:
        displayName: Callback URL
        type: string
        description: The URL for POST backs
        example: http://myserver.com?uuid=534cfd&schema=org.opent2t.sample.thermostat.superpopular&deviceId=123456
        required: false
      verificationRequest:
        displayName: Request for verification
        type: json
        description: Contents of a GET request to the callback
        required: false
    responses:
       200:
        body:
          application/json:
            example: |
                {
                    "expiration": "123456678",
                    "response": { "plain text response" }
                }
  delete:
    description: Unsubscribes to notifications on this device
    queryParameters:
      callbackUrl:
        displayName: Callback URL
        type: string
        description: The URL that was previously set up for a subscription
        example: http://myserver.com?uuid=534cfd&schema=org.opent2t.sample.thermostat.superpopular&deviceId=123456
        required: true
    responses:
      200:
        body:
          application/json:
          example: {}
        

        

